apiVersion: v1
kind: Pod
metadata:
  name: 
    labels:
        role: 
	spec:
	  containers:
	      - name: web
	            image: 
		          ports:
			          - name: web
				            containerPort: 80
					              protocol: TCP